### ISSUE TITLE
Exception message:Error: stderr maxBuffer exceeded.

### ISSUE THREAD

**Issue by orangejuicy** [Hacklone/private-bower#100]
The following exception happened time to time. After that the git daemon is stopped, but private-bower process is alive.
```
Exception message:Error: stderr maxBuffer exceeded.
    at Socket.<anonymous> (child_process.js:697:13)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at Pipe.onread (net.js:528:21)
Shutting down private-bower
Stopping git cache server
```

**Comment by Hacklone** [comment]
Nice catch, thanks :)

**Comment by jalbertcory** [comment]
I am running into this problem every couple of minutes.  Is there any way to set the maxBuffer to something larger or to solve the root of this.  The whole private bower idea becomes pretty useless if it goes down every 5 minutes.
[bower]  5/3/15 17:13:15   Exception message:Error: stderr maxBuffer exceeded.
    at Socket.<anonymous> (child_process.js:697:13)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at Pipe.onread (net.js:528:21)
[bower]  5/3/15 17:13:15   Shutting down private-bower
[bower]  5/3/15 17:13:15   Stopping git cache server

**Comment by johnrc** [comment]
May need to look at increasing the buffer size as indicated [here](http://stackoverflow.com/questions/23429499/stdout-buffer-issue-using-node-child-process) or use `childProcess.spawn` instead of `childProcess.exec`.

**Comment by jalbertcory** [comment]
Would that be the exec in the utils.js?

**Comment by jalbertcory** [comment]
So far so good, the registry has been up for 3 days and the components have around 1000 hits.
