### ISSUE TITLE
Crashes that leave git-deamon behind and block restart

### ISSUE THREAD

**Issue by oliversalzburg** [Hacklone/private-bower#112]
Recently I've seen this happen every other day. private-bower will die for some reason and will not be able to clean up the `git-deamon`. When it is then restarted, it fails to start, because `git-deamon` can't start.

Here's an excerpt from our logs:

```
[bower]  14/2/15 23:40:42   Pulled latest for ng-file-upload
[bower]  14/2/15 23:40:42   Pulled latest for jquery
[bower]  14/2/15 23:40:42   Pulled latest for moment
[bower]  14/2/15 23:40:42   Pulled latest for ng-grid
[bower]  14/2/15 23:43:06   Failed to initialize public repository cache
[bower]  14/2/15 23:43:06   Exception message:Error: stderr maxBuffer exceeded.
    at Socket.<anonymous> (child_process.js:707:13)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at Pipe.onread (net.js:529:21)
[bower]  14/2/15 23:43:06   Shutting down private-bower
[bower]  14/2/15 23:43:06   Stopping git cache server
error: Forever detected script exited with code: 0
error: Script restart attempt #1
[bower]  14/2/15 23:43:13   Refreshing public packages...
[bower]  14/2/15 23:43:13   Bower server started on port 5678
[bower]  14/2/15 23:43:13   Starting git cache server
[bower]  14/2/15 23:43:13   Failed to initialize public repository cache
[bower]  14/2/15 23:43:13   Exception message:Error: Command failed: [19740] Could not bind to ::1: Address already in use

```

**Comment by tkambler** [comment]
Ditto.

**Comment by RyanDickson** [comment]
I have experienced this frequently as well. As an interim fix I removed the verbose flag from the git daemon command in git-repo-cache.js and the maxBuffer on the exec has not been hit since for my setup.

**Comment by oliversalzburg** [comment]
@RyanDickson Thanks for the suggestion. I made that change on our server as well. So far, so good.
