### ISSUE TITLE
unregister not working

### ISSUE THREAD

**Issue by markuskremer** [Hacklone/private-bower#113]
I was unable to unregister packages.

```
$  curl --header "Content-Type:application/json" -d '{"packages":["modbusService"]}' http://MYSERVER:5678/removePackages
TypeError: undefined is not a function<br> &nbsp; &nbsp;at Object._removeRepo [as removeRepo] (/home/bower/bower/node_modules/private-bower/lib/repo-caches/repo-cache-bas...
```

Then I replaced 
```
!childDirectories.contains(repoName)
```
with
```
childDirectories.indexOf(repoName)===-1
```
in lib/repo-caches/repo-cache-base.js:47

and everything works file.

**Comment by Hacklone** [comment]
Thanks for noticing :) I'll fix that

**Comment by cobrowserAlex** [comment]
Could this solve my error as well.
Unregistering a package works but with error.

```
Removed package: package-name
TypeError: Object  has no method 'contains'
    at Object._removeRepo [as removeRepo] (/usr/lib/node_modules/private-bower/lib/repo-caches/repo-cache-base.js:47:30)
    at /usr/lib/node_modules/private-bower/lib/server.js:185:27
    at Array.forEach (native)
    at /usr/lib/node_modules/private-bower/lib/server.js:184:22
    at Array.forEach (native)
    at _removePackagesFromRepoCaches (/usr/lib/node_modules/private-bower/lib/server.js:183:20)
    at /usr/lib/node_modules/private-bower/lib/server.js:158:13
    at callbacks (/usr/lib/node_modules/private-bower/node_modules/express/lib/router/index.js:164:37)
    at param (/usr/lib/node_modules/private-bower/node_modules/express/lib/router/index.js:138:11)
    at pass (/usr/lib/node_modules/private-bower/node_modules/express/lib/router/index.js:145:5)
```
