### ISSUE TITLE
Windows: Cannot find module ('/:name/get)

### ISSUE THREAD

**Issue by jacobboland** [Hacklone/private-bower#132]
I am getting the following error when starting private-bower. 

[bower]  21/4/15 22:47:47   Refreshing public packages...
[bower]  21/4/15 22:47:48   Exception message:Error: Cannot find module './:name/get'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\...\node_modules\private-bower\lib\api\controllers\packages\index.js:10:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at loadControllerAtByName (C:\...\node_modules\private-bower\lib\application.js:51:30)
    at Array.forEach (native)
    at Object._loadControllers [as loadControllers] (C:\Users\jboland\AppData\Roaming\npm\node_modules\private-bower\lib\application.js:48:41)
    at _initializeService (C:\...\node_modules\private-bower\lib\main.js:63:21)
    at Object._start [as start] (C:\...\node_modules\private-bower\lib\main.js:34:9)
[bower]  21/4/15 22:47:48   Shutting down private-bower
C:\...\node_modules\private-bower\lib\application.js:60
        _listeningServer.close();
                        ^
TypeError: Cannot read property 'close' of undefined
    at Object._shutDown [as shutDown] (C:\...\node_modules\private-bower\lib\application.js:60:25)
    at _shutDown (C:\...\node_modules\private-bower\lib\main.js:88:21)
    at process.<anonymous> (C:\...\node_modules\private-bower\lib\main.js:79:13)
    at process.emit (events.js:107:17)
    at process._fatalException (node.js:236:26)

**Comment by Hacklone** [comment]
Oh, yes windows cannot handle :name as the file name

**Comment by jacobboland** [comment]
Thanks! It works for me, now.
