### ISSUE TITLE
Error cloning SVN package

### ISSUE THREAD

**Issue by Rorkal** [Hacklone/private-bower#162]
Hi!

I am having troubles using private-bower with SVN.

I am registering my package as follow:
>Package name: *socle*
>Package URL: *svn+http://svn-server/svn/socle/*

And I am having these errors when private-bower tries to clone the repo :
>*Error during "svn co svn+http://svn-server/svn/socle/ ./" in "D:\PrivateBower\svnRepoCache\socle"*
>*Failed to clone (maybe folder exists)svn+http://svn-server/svn/socle/*

I tried aside, the problems seems to be with **svn+**.
>C:\Users\User\Test>svn co svn+http://svn-server/svn/socle ./
>svn: E125002: Unable to connect to a repository at URL 'svn+http://svn-server/svn/socle'
>svn: E125002: Undefined tunnel scheme 'http'

But **svn+** is required in package URL for private-bower in order to make it a SVN repo...

Is that a bug or am i doing it wrong and there is an other way to configure SVN repo to make it work ?

Thanks.

**Comment by robsonflorentino** [comment]
Hi,

Sorry for my English.

I'm the same problem. But I tried fix the problem remove the "snv+" in the svn command, but I found another problem, after do the clone of the svn repository, couldn't load the details of the library, and as well I couldn't install my library. Follow the errors:

+  I cannot register by command line:

```
~  private-bower register angular-picklist svn+https://myhost/svn/mycompany/angular-picklist/trunk
[bower]  9/10/15 10:22:45   Refreshing public packages...
[bower]  9/10/15 10:22:45   Cached public packages loaded
[bower]  9/10/15 10:22:45   private-bower server started
[bower]  9/10/15 10:22:45   Exception message:Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at dns.js:72:18
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
```

+  When i register by the WebUi, cannot open the package details:

```
Failed to load package details! (Your private-bower server needs read access to this Git repository!)
```

+  When i try install my library, as that has registered as svn packages I had this error:

```
bower install angular-picklist
bower angular-picklist#*        cached git://localhost:6789/angular-picklist#1.0.0
bower angular-picklist#*      validate 1.0.0 against git://localhost:6789/angular-picklist#*
bower angular-picklist#*       ECMDERR Failed to execute "git ls-remote --tags --heads git://localhost:6789/angular-picklist", exit code of #128
```

**Comment by Rorkal** [comment]
Hi ! 

I never could make it work, so i abandonned the idea of using private-bower...

My bower.json file uses the svn URL like this and it works : 

```
"dependencies": {
    "socle": "svn+http://my_url/svn/socle#trunk"    
  },
```

**Comment by robsonflorentino** [comment]
Hi Rorkal!

I'm coming to that conclusion.

I've had debugged some parts of the source trying to find that was wrong. I came to find some parts of source as well at the part where find packages details, that don't implement svn methods to find informations.

This project is good, but cannot implant it in my company, once that I have a very long historic of the projects on svn.

When I have more time, I want fork it to try implement more resources of SVN.

Sorry form my English, and tanks.
