### ISSUE TITLE
not able to start private bower

### ISSUE THREAD

**Issue by kuldeepkeshwar** [Hacklone/private-bower#206]
I'm trying to start private bower after installing the latest version
but i'm getting the below error. 

kuldeep@kuldeep-ubuntu:~/Desktop/private-bower$ private-bower --config ./myBowerConfig.json
[bower]  8/12/15 19:20:14   Exception message:SyntaxError: Unexpected token }
    at Object.parse (native)
    at Object._loadConfiguration [as loadConfiguration] (/usr/lib/node_modules/private-bower/lib/infrastructure/configurationManager.js:28:31)
    at Object._start [as start] (/usr/lib/node_modules/private-bower/lib/main.js:32:30)
    at Object.<anonymous> (/usr/lib/node_modules/private-bower/bin/private-bower:3:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
[bower]  8/12/15 19:20:14   Shutting down private-bower

/usr/lib/node_modules/private-bower/lib/application.js:70
        _listeningServer.close();
                         ^
TypeError: Cannot call method 'close' of undefined
    at Object._shutDown [as shutDown] (/usr/lib/node_modules/private-bower/lib/application.js:70:26)
    at _shutDown (/usr/lib/node_modules/private-bower/lib/main.js:95:21)
    at process.<anonymous> (/usr/lib/node_modules/private-bower/lib/main.js:86:13)
    at process.EventEmitter.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)

**Comment by kuldeepkeshwar** [comment]
working now, json in config.son was invalid
