### ISSUE TITLE
"Cannot read property 'registryFile' of undefined" error when starting with --config option

### ISSUE THREAD

**Issue by nfriend** [Hacklone/private-bower#241]
I'm sure I'm just doing something wrong, since I can't seem to find reference to this error anywhere else on the internet.  When I start private-bower like this:

```
private-bower --config .\private-bower-config.json
```

I get the following error:

```
[bower]  27/5/16 14:32:17   Exception message:TypeError: Cannot read property 'registryFile' of undefined
    at setConfigValues (C:\Users\username\AppData\Roaming\nvm\v4.4.4\node_modules\private-bower\lib\infrastructure\configurationManager.js:44:84)
    at Object._loadConfiguration [as loadConfiguration] (C:\Users\username\AppData\Roaming\nvm\v4.4.4\node_modules\private-bower\lib\infrastructure\configurationManager.js:32:9)
    at Object._start [as start] (C:\Users\username\AppData\Roaming\nvm\v4.4.4\node_modules\private-bower\lib\main.js:32:30)
    at Object.<anonymous> (C:\Users\username\AppData\Roaming\nvm\v4.4.4\node_modules\private-bower\bin\private-bower:3:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
[bower]  27/5/16 14:32:17   Shutting down private-bower
C:\Users\username\AppData\Roaming\nvm\v4.4.4\node_modules\private-bower\lib\application.js:70
        _listeningServer.close();
                        ^

TypeError: Cannot read property 'close' of undefined
    at Object._shutDown [as shutDown] (C:\Users\username\AppData\Roaming\nvm\v4.4.4\node_modules\private-bower\lib\application.js:70:25)
    at _shutDown (C:\Users\username\AppData\Roaming\nvm\v4.4.4\node_modules\private-bower\lib\main.js:95:21)
    at process.<anonymous> (C:\Users\username\AppData\Roaming\nvm\v4.4.4\node_modules\private-bower\lib\main.js:86:13)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:224:26)
```

Here's what my `private-bower-config.json` looks like:

```json
{
    "registryFile": "./bowerRepository.json"
}
```

I tried creating an empty `bowerRepository.json` file, but that didn't seem to change anything.

Other info:
- `private-bower` version: 1.1.7
- node version: tested on 4.4.4 and 5.6.0
- OS version: Windows 8.1
- Browser version: NA
- Bower client: NA

**Comment by nfriend** [comment]
Just tried it with a config .json that contained _all_ of the properties listed in example config file in the documentation, and now I'm not getting this error.  Not sure which of the properties was causing this error.  It might be worth noting in the documentation which properties are required and which are optional to avoid this confusion.
