### ISSUE TITLE
How to restart private-bower

### ISSUE THREAD

**Issue by alansouzati** [Hacklone/private-bower#84]
Hi, is there a way to use something like 'private-bower restart' ?

**Comment by andham** [comment]
The wiki doesn't mention that you need to be authentiated to use the restart function. Is that true? Seems strange to allow anonymous to restart...

**Comment by Hacklone** [comment]
No you'll have to be authenticated :)

**Comment by Hacklone** [comment]
Can I close this issue?

**Comment by andham** [comment]
I just tried the restart POST call, but it fails on Windows. private-bower started from command-line, not as a service.

> [bower]  2/2/15 13:46:10   Shutting down server for restart
[bower]  2/2/15 13:46:10   Restarting private-bower with config set to C:\xxx\bower-proxy\bowerProxyConfig.json
[bower]  2/2/15 13:46:10   Shutting down private-bower
[bower]  2/2/15 13:46:10   Stopping git cache server
[bower]  2/2/15 13:46:10   Exception message:Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
[bower]  2/2/15 13:46:10   Shutting down private-bower
[bower]  2/2/15 13:46:10   Stopping git cache server

**Comment by Hacklone** [comment]
Could you try this with the latest version?

**Comment by Hacklone** [comment]
Closing this due to inactivity.
